### ISSUE TITLE
export two function is error

### ISSUE THREAD

**Issue by niunaiyi** [zeroKilo/ProxyDllMaker#1]
i export two function, code is ok.
but  when be called, error:
System.AccessViolationException: 

export one function,everything is fine。

**Comment by zeroKilo** [comment]
without providing information I cant help you

**Comment by niunaiyi** [comment]
wow, thanks for your reply and your help.
i make a proxy dll with your tools. 
i want to do something when some function be called. 

i have a  "TSCLIB.dll“ from [tscprinters.com](http://www.tscprinters.com) and get  sample code to call dll:

this is sample code generated by your tool:[TSCLIB](https://github.com/niunaiyi/TSCLIB)
export openport is fine, but export two function:openport  and windowsfont,  TSCLIB.DLL VB.NET_Example is not work. 
and Exception is :"System.AccessViolationException: Attempted to read or write protected memory."

thanks for your help again.

[TSCLIB.DLL_VB.NET_Example.zip](https://github.com/zeroKilo/ProxyDllMaker/files/3124619/TSCLIB.DLL_VB.NET_Example.zip)

**Comment by niunaiyi** [comment]
i follow from [youtube](https://www.youtube.com/watch?v=lAY_ww8SNmM)

**Comment by zeroKilo** [comment]
well, I looked at your code, im not sure if you can simply replace the 2 functions the way you do. in theory it should be possible, yes, but I think you have to make an exports.def for this, so the linker knows that it has to put them in the export table. then im not sure if the order of exports could get messed up this way (you can call functions of dlls by ordinal too, not only name) also maybe try different calling conventions like __stdcall, _cdecl or WINAPI. The way I would solve this would be: make all exports with "links" and in your code use ms detours or minhook to detour the functions

PS: I cant open any of your links, sry

**Comment by niunaiyi** [comment]
i try the way you told me , not success。maybe the best way is yours. i update the comment. can you told me something can help me with ProxyDllMaker?

**Comment by zeroKilo** [comment]
well first try to make a proxy dll that does nothing other than showing a messagebox (https://pastebin.com/syXuFrSF) 

simply generate all with links and make the dll (remember to compile it to release). once that works, aka you get a messagebox when the program starts now, you are at least sure it works. 

now to detour your functions, you need windows detours for example (https://github.com/Microsoft/Detours) with that I wrote you an example how you detour one function, you have to repeat if for all functions you need: https://pastebin.com/sz4QHF4L , the idea is to find the loaded function's address and use that to overwrite it on runtime. 

more example for detours: https://www.codeproject.com/Articles/30140/API-Hooking-with-MS-Detours 

you can use this f.e. to open a console to print out stuff https://github.com/zeroKilo/BFP4FToolsWV/blob/master/Zlib122_2010/zlib122/Hack.cpp#L21 (also notice how detours library is included in line 5 and 6!

greetz WV

**Comment by niunaiyi** [comment]
can i get function's address with CFF or IDA ?

![无标题1](https://user-images.githubusercontent.com/26132379/56908898-ce1d8780-6ad9-11e9-8b45-f16f0c5e59bc.png)
![无标题2](https://user-images.githubusercontent.com/26132379/56908900-ce1d8780-6ad9-11e9-8a3f-c5876a1aaab1.png)

**Comment by zeroKilo** [comment]
you can use the baseaddress of the dll and offsets that maybe, but why not use the winapi functions that are made for it as I showed in my code? (GetModuleHandleA and GetProcAddress) btw, you can also use the ordinal of an export instead of the functionname, google msdn for GetProcAddress

greetz

**Comment by niunaiyi** [comment]
this is my paste, and it work!!! but how can i get function's parameters?
extern "C" int Proxy_windowsfont(int a1, int a2, int a3, int a4, int a5, char a6, LPCSTR lpString2, LPCSTR lpString)

this is my paste [https://pastebin.com/gzvpmcYx](https://pastebin.com/gzvpmcYx)

**Comment by zeroKilo** [comment]
in your paste you retrieve the function pointers address, but you do no detouring/hooking! reread my code! (https://pastebin.com/sz4QHF4L), also dont add the attribute "extern" because your dll doesnt want to export it, you want it to point to the real function which in turn you are going to overwrite. google detouring/hooking and look at my code, I already did the work for one functions, just redo it for the other function. to find the arguments, just use ida, and if you are unsure about a parameter define it as DWORD (its all 32bit anyway), as long as the count and the calling convention fits, it should work

**Comment by niunaiyi** [comment]
DetourFunction no found?

**Comment by zeroKilo** [comment]
dude im not going to repeat myself over and over, its part of ms detours, I told you already to google it and examples of it, here the direct quote:

"
now to detour your functions, you need windows detours for example (https://github.com/Microsoft/Detours) with that I wrote you an example how you detour one function, you have to repeat if for all functions you need: https://pastebin.com/sz4QHF4L , the idea is to find the loaded function's address and use that to overwrite it on runtime.

more example for detours: https://www.codeproject.com/Articles/30140/API-Hooking-with-MS-Detours

"

EDIT: here an example on how to include detours lib
https://github.com/zeroKilo/BFP4FToolsWV/blob/master/Zlib122_2010/zlib122/Hack.cpp#L5
and the line below it, so in total:

#pragma comment(lib, "detours.lib")
#include "detours.h"

EDIT2: heres how its used in that project:

https://github.com/zeroKilo/BFP4FToolsWV/blob/master/Zlib122_2010/zlib122/Hack.cpp#L229

**Comment by niunaiyi** [comment]
WOW!!!
finally, its worked!!
learn from your ZLIB122, it's a very good sample!!!!!!
thanks thanks thanks!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
dont know how to thanks.
![image](https://user-images.githubusercontent.com/26132379/57458503-10964f80-72a4-11e9-94cc-6c50bb207415.png)
